# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r_binary_packages:
- ape
- assertthat
- backports
- base64enc
- cellranger
- chron
- classInt
- cli
- crayon
- curl
- DBI
- digest
- e1071
- ellipsis
- evaluate
- fansi
- glue
- highr
- hms
- htmltools
- jsonlite
- knitr
- magrittr
- markdown
- mime
- pillar
- pkgconfig
- prettyunits
- progress
- R6
- Rcpp
- readxl
- rematch
- remotes
- rlang
- rmarkdown
- sf
- stringi
- stringr
- tibble
- tinytex
- units
- utf8
- vctrs
- xfun
- yaml
- zeallot
