# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
cache: packages

matrix:
  include:
  - r: release
    os: linux
    env: DEPLOY="true"	
  - r: devel
    os: linux
    env: DEPLOY="false"	
  - r: release
    os: osx
    env: DEPLOY="false"	

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

brew_packages:
  - udunits

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    condition: $DEPLOY = 'true'

r_packages:
- Rcpp
- units
- devtools
- ape # from here down used to use r_binary_packages but the PPA that supplied those is temporarily down
- assertthat
- backports
- base64enc
- cellranger
- chron
- classInt
- cli
- crayon
- curl
- DBI
- digest
- e1071
- ellipsis
- evaluate
- fansi
- glue
- highr
- hms
- htmltools
- jsonlite
- knitr
- magrittr
- markdown
- mime
- pillar
- pkgconfig
- pkgdown
- prettyunits
- progress
- R6
- readxl
- rematch
- remotes
- rlang
- rmarkdown
- sf
- stringi
- stringr
- tibble
- tinytex
- utf8
- vctrs
- xfun
- yaml
- zeallot

